### ISSUE TITLE
PEAR no longer available

### ISSUE THREAD

**Issue by TonyaWard** [LangilleLab/microbiome_helper#11]
PEAR, used for paired end joining in your pipeline, is no longer available.  The website for PEAR you link to is still up, but downloads and the git repo are gone.

**Comment by gavinmdouglas** [comment]
Hey Tonya,

It looks like PEAR has switched to be commercial for non-academic users. If you are an academic researcher you can download PEAR from the “new downloads page” on the right side-bar.


Best,

Gavin

**Comment by TonyaWard** [comment]
Great! Thanks!

Tonya
