### ISSUE TITLE
Question about Random Forest

### ISSUE THREAD

**Issue by whynotlih** [LangilleLab/microbiome_helper#21]
Hi
I had a OTU table like your Random Forest Tutorial. I want to find the OTUs that has the greatest contribution to the sample groups by random forest and the samples belong to different host's gut, what should i do? The result may like below, thanks!

![image](https://user-images.githubusercontent.com/27685280/34830033-964f2aa6-f71d-11e7-97af-2a4a1ad1d107.png)

**Comment by gavinmdouglas** [comment]
Hi there,

The mean decrease in accuracy refers to how much the accuracy decreases when that OTU's relative abundance values are scrambled across samples. For OTU71 the accuracy decreases by 1.33% when it is scrambled and it looks to be the most informative taxon based on this set.

Does that answer your question? In the future you can ask questions on our googlegroup: https://groups.google.com/forum/#!forum/microbiome-helper
