### ISSUE TITLE
About paired-end fastq data

### ISSUE THREAD

**Issue by cam315** [LangilleLab/microbiome_helper#23]
@mlangill I am new to metaphlan2 and humann2. My question is related to the paired-end data. What will a good solution for paired end data? In addition, shall I directly feed the raw fastq data to metaphlan2.py or it is better to put the fastq file after quality control or assembling? Thank you in advance

**Comment by gavinmdouglas** [comment]
Hi @cam315, the humann2 authors address this question here: https://bitbucket.org/biobakery/humann2/wiki/Home#markdown-header-humann2-and-paired-end-sequencing-data

It is definitely better to quality control your reads before running metaphlan2 (you'll be less likely to get false positives).

There are google groups for both the humann2 and metaphlan2 tools, which you may find useful by the way.

**Comment by cam315** [comment]
@gavinmdouglas Thank you for your explanation. Sorry to have disturbed you with this question here, I should have checked the user manual carefully.
