### ISSUE TITLE
Error in dada2_filter.R

### ISSUE THREAD

**Issue by caijian89** [LangilleLab/microbiome_helper#25]
When I did the filter process with my own data following dada tutorials, the error stopped me.

My commands were `dada2_filter.R -f rawdata --truncLen 230,230 --maxN 0 --maxEE 2,2 --truncQ 2 --threads 1 --f_match _R1_.*fastq.gz --r_match _R2_.*fastq.gz --verbose TRUE`

The runing message were 
`Running DADA2 version: 1.4.0 
Loading required package: Rcpp
Loading required package: methods
Running filterAndTrim function with the below options.
Paired-end mode
fwd =rawdata/13_R1_001.fastq.gz,rawdata/14_R1_001.fastq.gz,rawdata/15_R1_001.fastq.gz,rawdata/1_R1_001.fastq.gz,rawdata/20_R1_001.fastq.gz,rawdata/22_R1_001.fastq.gz,rawdata/23_R1_001.fastq.gz,rawdata/3_R1_001.fastq.gz,rawdata/5_R1_001.fastq.gz,rawdata/6_R1_001.fastq.gz,rawdata/7_R1_001.fastq.gz,rawdata/8_R1_001.fastq.gz,rawdata/9_R1_001.fastq.gz,rawdata/B1_R1_001.fastq.gz,rawdata/B2_R1_001.fastq.gz,rawdata/B3_R1_001.fastq.gz,rawdata/B4_R1_001.fastq.gz,rawdata/B5_R1_001.fastq.gz,rawdata/B6_R1_001.fastq.gz,rawdata/B7_R1_001.fastq.gz,rawdata/B8_R1_001.fastq.gz,rawdata/B9_R1_001.fastq.gz,rawdata/L11_R1_001.fastq.gz,rawdata/L12_R1_001.fastq.gz,rawdata/LL1_R1_001.fastq.gz,rawdata/MK_10_R1_001.fastq.gz,rawdata/MK_11_R1_001.fastq.gz,rawdata/MK_12_R1_001.fastq.gz,rawdata/MK_13_R1_001.fastq.gz,rawdata/MK_14_R1_001.fastq.gz,rawdata/MK_15_R1_001.fastq.gz,rawdata/MK_16_R1_001.fastq.gz,rawdata/MK_17_R1_001.fastq.gz,rawdata/MK_18_R1_001.fastq.gz,rawdata/MK_19_R1_001.fastq.gz,rawdata/MK_1_R1_001.fastq.gz,rawdata/MK_20_R1_001.fastq.gz,rawdata/MK_21_R1_001.fastq.gz,rawdata/MK_22_R1_001.fastq.gz,rawdata/MK_23_R1_001.fastq.gz,rawdata/MK_24_R1_001.fastq.gz,rawdata/MK_2_R1_001.fastq.gz,rawdata/MK_3_R1_001.fastq.gz,rawdata/MK_4_R1_001.fastq.gz,rawdata/MK_5_R1_001.fastq.gz,rawdata/MK_6_R1_001.fastq.gz,rawdata/MK_7_R1_001.fastq.gz,rawdata/MK_8_R1_001.fastq.gz,rawdata/MK_9_R1_001.fastq.gz,rawdata/QL_5_10_R1_001.fastq.gz,rawdata/QL_5_11_R1_001.fastq.gz,rawdata/QL_5_12_R1_001.fastq.gz,rawdata/QL_5_13_R1_001.fastq.gz,rawdata/QL_5_14_R1_001.fastq.gz,rawdata/QL_5_15_R1_001.fastq.gz,rawdata/QL_5_16_R1_001.fastq.gz,rawdata/QL_5_17_R1_001.fastq.gz,rawdata/QL_5_18_R1_001.fastq.gz,rawdata/QL_5_19_R1_001.fastq.gz,rawdata/QL_5_1_R1_001.fastq.gz,rawdata/QL_5_20_R1_001.fastq.gz,rawdata/QL_5_21_R1_001.fastq.gz,rawdata/QL_5_24_R1_001.fastq.gz,rawdata/QL_5_25_R1_001.fastq.gz,rawdata/QL_5_2_R1_001.fastq.gz,rawdata/QL_5_3_R1_001.fastq.gz,rawdata/QL_5_4_R1_001.fastq.gz,rawdata/QL_5_5_R1_001.fastq.gz,rawdata/QL_5_6_R1_001.fastq.gz,rawdata/QL_5_7_R1_001.fastq.gz,rawdata/QL_5_8_R1_001.fastq.gz,rawdata/QL_5_9_R1_001.fastq.gz,rawdata/QL_7_10_R1_001.fastq.gz,rawdata/QL_7_11_R1_001.fastq.gz,rawdata/QL_7_12_R1_001.fastq.gz,rawdata/QL_7_13_R1_001.fastq.gz,rawdata/QL_7_14_R1_001.fastq.gz,rawdata/QL_7_15_R1_001.fastq.gz,rawdata/QL_7_16_R1_001.fastq.gz,rawdata/QL_7_17_R1_001.fastq.gz,rawdata/QL_7_18_R1_001.fastq.gz,rawdata/QL_7_19_R1_001.fastq.gz,rawdata/QL_7_1_R1_001.fastq.gz,rawdata/QL_7_20_R1_001.fastq.gz,rawdata/QL_7_21_R1_001.fastq.gz,rawdata/QL_7_22_R1_001.fastq.gz,rawdata/QL_7_24_R1_001.fastq.gz,rawdata/QL_7_2_R1_001.fastq.gz,rawdata/QL_7_3_R1_001.fastq.gz,rawdata/QL_7_4_R1_001.fastq.gz,rawdata/QL_7_5_R1_001.fastq.gz,rawdata/QL_7_6_R1_001.fastq.gz,rawdata/QL_7_8_R1_001.fastq.gz,rawdata/QL_7_9_R1_001.fastq.gz,rawdata/QL_9_10_R1_001.fastq.gz,rawdata/QL_9_11_R1_001.fastq.gz,rawdata/QL_9_13_R1_001.fastq.gz,rawdata/QL_9_16_R1_001.fastq.gz,rawdata/QL_9_17_R1_001.fastq.gz,rawdata/QL_9_18_R1_001.fastq.gz,rawdata/QL_9_19_R1_001.fastq.gz,rawdata/QL_9_1_R1_001.fastq.gz,rawdata/QL_9_20_R1_001.fastq.gz,rawdata/QL_9_2_R1_001.fastq.gz,rawdata/QL_9_3_R1_001.fastq.gz,rawdata/QL_9_4_R1_001.fastq.gz,rawdata/QL_9_5_R1_001.fastq.gz,rawdata/QL_9_6_R1_001.fastq.gz,rawdata/QL_9_8_R1_001.fastq.gz,rawdata/QL_9_9_R1_001.fastq.gz
filt =filtered_fastqs/13_R1_filt.fastq.gz,filtered_fastqs/14_R1_filt.fastq.gz,filtered_fastqs/15_R1_filt.fastq.gz,filtered_fastqs/1_R1_filt.fastq.gz,filtered_fastqs/20_R1_filt.fastq.gz,filtered_fastqs/22_R1_filt.fastq.gz,filtered_fastqs/23_R1_filt.fastq.gz,filtered_fastqs/3_R1_filt.fastq.gz,filtered_fastqs/5_R1_filt.fastq.gz,filtered_fastqs/6_R1_filt.fastq.gz,filtered_fastqs/7_R1_filt.fastq.gz,filtered_fastqs/8_R1_filt.fastq.gz,filtered_fastqs/9_R1_filt.fastq.gz,filtered_fastqs/B1_R1_filt.fastq.gz,filtered_fastqs/B2_R1_filt.fastq.gz,filtered_fastqs/B3_R1_filt.fastq.gz,filtered_fastqs/B4_R1_filt.fastq.gz,filtered_fastqs/B5_R1_filt.fastq.gz,filtered_fastqs/B6_R1_filt.fastq.gz,filtered_fastqs/B7_R1_filt.fastq.gz,filtered_fastqs/B8_R1_filt.fastq.gz,filtered_fastqs/B9_R1_filt.fastq.gz,filtered_fastqs/L11_R1_filt.fastq.gz,filtered_fastqs/L12_R1_filt.fastq.gz,filtered_fastqs/LL1_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/MK_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz,filtered_fastqs/QL_R1_filt.fastq.gz
rev =rawdata/13_R2_001.fastq.gz,rawdata/14_R2_001.fastq.gz,rawdata/15_R2_001.fastq.gz,rawdata/1_R2_001.fastq.gz,rawdata/20_R2_001.fastq.gz,rawdata/22_R2_001.fastq.gz,rawdata/23_R2_001.fastq.gz,rawdata/3_R2_001.fastq.gz,rawdata/5_R2_001.fastq.gz,rawdata/6_R2_001.fastq.gz,rawdata/7_R2_001.fastq.gz,rawdata/8_R2_001.fastq.gz,rawdata/9_R2_001.fastq.gz,rawdata/B1_R2_001.fastq.gz,rawdata/B2_R2_001.fastq.gz,rawdata/B3_R2_001.fastq.gz,rawdata/B4_R2_001.fastq.gz,rawdata/B5_R2_001.fastq.gz,rawdata/B6_R2_001.fastq.gz,rawdata/B7_R2_001.fastq.gz,rawdata/B8_R2_001.fastq.gz,rawdata/B9_R2_001.fastq.gz,rawdata/L11_R2_001.fastq.gz,rawdata/L12_R2_001.fastq.gz,rawdata/LL1_R2_001.fastq.gz,rawdata/MK_10_R2_001.fastq.gz,rawdata/MK_11_R2_001.fastq.gz,rawdata/MK_12_R2_001.fastq.gz,rawdata/MK_13_R2_001.fastq.gz,rawdata/MK_14_R2_001.fastq.gz,rawdata/MK_15_R2_001.fastq.gz,rawdata/MK_16_R2_001.fastq.gz,rawdata/MK_17_R2_001.fastq.gz,rawdata/MK_18_R2_001.fastq.gz,rawdata/MK_19_R2_001.fastq.gz,rawdata/MK_1_R2_001.fastq.gz,rawdata/MK_20_R2_001.fastq.gz,rawdata/MK_21_R2_001.fastq.gz,rawdata/MK_22_R2_001.fastq.gz,rawdata/MK_23_R2_001.fastq.gz,rawdata/MK_24_R2_001.fastq.gz,rawdata/MK_2_R2_001.fastq.gz,rawdata/MK_3_R2_001.fastq.gz,rawdata/MK_4_R2_001.fastq.gz,rawdata/MK_5_R2_001.fastq.gz,rawdata/MK_6_R2_001.fastq.gz,rawdata/MK_7_R2_001.fastq.gz,rawdata/MK_8_R2_001.fastq.gz,rawdata/MK_9_R2_001.fastq.gz,rawdata/QL_5_10_R2_001.fastq.gz,rawdata/QL_5_11_R2_001.fastq.gz,rawdata/QL_5_12_R2_001.fastq.gz,rawdata/QL_5_13_R2_001.fastq.gz,rawdata/QL_5_14_R2_001.fastq.gz,rawdata/QL_5_15_R2_001.fastq.gz,rawdata/QL_5_16_R2_001.fastq.gz,rawdata/QL_5_17_R2_001.fastq.gz,rawdata/QL_5_18_R2_001.fastq.gz,rawdata/QL_5_19_R2_001.fastq.gz,rawdata/QL_5_1_R2_001.fastq.gz,rawdata/QL_5_20_R2_001.fastq.gz,rawdata/QL_5_21_R2_001.fastq.gz,rawdata/QL_5_24_R2_001.fastq.gz,rawdata/QL_5_25_R2_001.fastq.gz,rawdata/QL_5_2_R2_001.fastq.gz,rawdata/QL_5_3_R2_001.fastq.gz,rawdata/QL_5_4_R2_001.fastq.gz,rawdata/QL_5_5_R2_001.fastq.gz,rawdata/QL_5_6_R2_001.fastq.gz,rawdata/QL_5_7_R2_001.fastq.gz,rawdata/QL_5_8_R2_001.fastq.gz,rawdata/QL_5_9_R2_001.fastq.gz,rawdata/QL_7_10_R2_001.fastq.gz,rawdata/QL_7_11_R2_001.fastq.gz,rawdata/QL_7_12_R2_001.fastq.gz,rawdata/QL_7_13_R2_001.fastq.gz,rawdata/QL_7_14_R2_001.fastq.gz,rawdata/QL_7_15_R2_001.fastq.gz,rawdata/QL_7_16_R2_001.fastq.gz,rawdata/QL_7_17_R2_001.fastq.gz,rawdata/QL_7_18_R2_001.fastq.gz,rawdata/QL_7_19_R2_001.fastq.gz,rawdata/QL_7_1_R2_001.fastq.gz,rawdata/QL_7_20_R2_001.fastq.gz,rawdata/QL_7_21_R2_001.fastq.gz,rawdata/QL_7_22_R2_001.fastq.gz,rawdata/QL_7_24_R2_001.fastq.gz,rawdata/QL_7_2_R2_001.fastq.gz,rawdata/QL_7_3_R2_001.fastq.gz,rawdata/QL_7_4_R2_001.fastq.gz,rawdata/QL_7_5_R2_001.fastq.gz,rawdata/QL_7_6_R2_001.fastq.gz,rawdata/QL_7_8_R2_001.fastq.gz,rawdata/QL_7_9_R2_001.fastq.gz,rawdata/QL_9_10_R2_001.fastq.gz,rawdata/QL_9_11_R2_001.fastq.gz,rawdata/QL_9_13_R2_001.fastq.gz,rawdata/QL_9_16_R2_001.fastq.gz,rawdata/QL_9_17_R2_001.fastq.gz,rawdata/QL_9_18_R2_001.fastq.gz,rawdata/QL_9_19_R2_001.fastq.gz,rawdata/QL_9_1_R2_001.fastq.gz,rawdata/QL_9_20_R2_001.fastq.gz,rawdata/QL_9_2_R2_001.fastq.gz,rawdata/QL_9_3_R2_001.fastq.gz,rawdata/QL_9_4_R2_001.fastq.gz,rawdata/QL_9_5_R2_001.fastq.gz,rawdata/QL_9_6_R2_001.fastq.gz,rawdata/QL_9_8_R2_001.fastq.gz,rawdata/QL_9_9_R2_001.fastq.gz
filt.rev =filtered_fastqs/13_R2_filt.fastq.gz,filtered_fastqs/14_R2_filt.fastq.gz,filtered_fastqs/15_R2_filt.fastq.gz,filtered_fastqs/1_R2_filt.fastq.gz,filtered_fastqs/20_R2_filt.fastq.gz,filtered_fastqs/22_R2_filt.fastq.gz,filtered_fastqs/23_R2_filt.fastq.gz,filtered_fastqs/3_R2_filt.fastq.gz,filtered_fastqs/5_R2_filt.fastq.gz,filtered_fastqs/6_R2_filt.fastq.gz,filtered_fastqs/7_R2_filt.fastq.gz,filtered_fastqs/8_R2_filt.fastq.gz,filtered_fastqs/9_R2_filt.fastq.gz,filtered_fastqs/B1_R2_filt.fastq.gz,filtered_fastqs/B2_R2_filt.fastq.gz,filtered_fastqs/B3_R2_filt.fastq.gz,filtered_fastqs/B4_R2_filt.fastq.gz,filtered_fastqs/B5_R2_filt.fastq.gz,filtered_fastqs/B6_R2_filt.fastq.gz,filtered_fastqs/B7_R2_filt.fastq.gz,filtered_fastqs/B8_R2_filt.fastq.gz,filtered_fastqs/B9_R2_filt.fastq.gz,filtered_fastqs/L11_R2_filt.fastq.gz,filtered_fastqs/L12_R2_filt.fastq.gz,filtered_fastqs/LL1_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/MK_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz,filtered_fastqs/QL_R2_filt.fastq.gz
compress =TRUE
truncQ =2
truncLen =230,230
trimLeft =0
maxLen =Inf
minLen =20
maxN =0
minQ =0
maxEE =2,2
rm.phix =TRUE
multithread =FALSE
n =100000
matchIDs =FALSE
id.sep =\s
id.field =NULL
verbose =TRUE

Error in filterAndTrim(fwd = forward_in, filt = forward_out, rev = reverse_in,  : 
  All output files must be distinct.
Execution halted`

However, I had noticed that the filenames of output files were imcompleted, which resulted in the same names among most of out files. 

Could you give some advices, I am fresh with linux OS.

Thanks a lot

**Comment by caijian89** [comment]
Many thanks, as your suggestions，i manually renamed the filenames in a stupid way. The problem was resolved. But, another warning message was occurring. 
`Running DADA2 version: 1.4.0 
Loading required package: Rcpp
Loading required package: methods
'BiocParallel' did not register default BiocParallelParams:
  invalid class “MulticoreParam” object: 1: ‘cluster’, ‘.clusterargs’, ‘.uid’, ‘RNGseed’ must be length 1
invalid class “MulticoreParam” object: 2: ‘.clusterargs’, ‘.controlled’, ‘logdir’, ‘resultdir’ must be length 1
Running filterAndTrim function with the below options.
Warning message:
In is.na(x[[i]]) :
  is.na() applied to non-(list or vector) of type 'environment'
Paired-end mode
`

**Comment by gavinmdouglas** [comment]
Hi again,

Are you running this script on our virtual box? If so what version? If you are running it on your own computer then you may want to try the fix recommended here (installing a different version of bioconductor): https://support.bioconductor.org/p/95306/ <https://support.bioconductor.org/p/95306/>

**Comment by caijian89** [comment]
Thanks for the kind reply.
Well, I am running the wrapper workflow on the microbiome_helper virtual box (version 2.2.1).

**Comment by caijian89** [comment]
@gavinmdouglas  Thanks for your quick, useful reply!
I resolved the warning message by updating the BiocParallel packages in R console.

**Comment by gavinmdouglas** [comment]
Hmm I think something else might have changed in your environment before updating BiocParallel. I am able to run the tutorial workflow on v2.2.1 (https://github.com/LangilleLab/microbiome_helper/wiki/DADA2-16S-Chemerin-Tutorial) without the problem you ran into. It's also possible that something about your dataset caused that error, but I'm not sure what it would be based on the error you received.

The taxonomy classifier for the DADA2 workflow is also working fine for me on v2.2.1 (regarding issue https://github.com/LangilleLab/microbiome_helper/issues/26). Is it possible that your sequences are on the opposite strand or wouldn't match the DADA2 reference database for some other reason? If not then I think there might be some new compatibility issue that was caused when you updated the R environment. If you want to send me a raw file or intermediate file privately then I am happy to help you troubleshoot.

**Comment by caijian89** [comment]
Hi  @gavinmdouglas 
How can I send the raw sequence files to you, the compressed file are still too large (>2.5 Gb)


And there are other questions，I was also wondering about the log files from the dada inferred process.
I noticed that the derep_sum reads number were identical with the denoise read, is that common? And I also want to understand what is the unique sequences, are they as same as the Exact sequence variants?

[dada2_inferred_read_counts.txt](https://github.com/LangilleLab/microbiome_helper/files/1835928/dada2_inferred_read_counts.txt)

**Comment by caijian89** [comment]
Well, I am sure now that my sequences are on the opposite strand and without setting the tryRC to TRUE.
I upload the fasta files to RDP website to assign the taxonomy, and it works well. And the results showed that most of my sequences were reversed to obtain the assignments. Any way, I try to resolve this by changing the tryRC default setttings to TRUE. Hope it would work on my computer.

Your patient guidance is so appreciated!
