### ISSUE TITLE
Problems running metaphlan_to_stamp.pl

### ISSUE THREAD

**Issue by little-hunter** [LangilleLab/microbiome_helper#29]
Dear author:
         I'm trying to convert my results from metaphlan2 to stamp input file by using your metaphlan_to_stamp.pl. And below is the command I used. 
`metaphlan_to_stamp.pl` utils/metaphlan_merged_all.txt > `metaphlan_merged_all.spf`
However, I always get some Error information
"syntax error at metaphlan_to_stamp.pl line 5, near "<"
Excessively long <> operator at metaphlan_to_stamp.pl line 16."
Could  you please help me to know why? How can I solve this problem?

**Comment by gavinmdouglas** [comment]
Thanks for making the issue for this error. Are you using our virtual box image? If not, what version of Perl are you running?

Thanks,

Gavin

**Comment by gavinmdouglas** [comment]
Closed due to inactivity.
