### ISSUE TITLE
Biom error for convert_dada2_out.R

### ISSUE THREAD

**Issue by jvhagey** [LangilleLab/microbiome_helper#30]
Biom has been deprecated. Biomformat available through bioconductor is the official package.

**Comment by gavinmdouglas** [comment]
Thanks for pointing this out @jvhagey. I'll make a fix for this issue this week.

**Comment by gavinmdouglas** [comment]
I changed the script to not be dependent on either library now. It now outputs the table in legacy TSV format which can be converted to an HDF5 BIOM afterwards if needed.

**Comment by jvhagey** [comment]
Thanks @gavinmdouglas this sure saved me a lot of time!
