### ISSUE TITLE
Error with the VM

### ISSUE THREAD

**Issue by cristianrohr** [LangilleLab/microbiome_helper#33]
Hello,
I tried to download both VM version, and the file seems to be corrupted, do you have the md5sum to check?

thanks

**Comment by gavinmdouglas** [comment]
Hey,

Sorry you're running into this problem. The md5sum values are:

6d7eee3e0c0b4cfcf2e094a5e9869849  MicrobiomeHelper_v2.3.0.ova
ef6f305be7c81454994598f56a9372d8  MicrobiomeHelper_amplicon_v0.4.ova

Best,

Gavin

**Comment by cristianrohr** [comment]
Hello Gavin,

the md5sum is correct

[crohr@z800 microbiome_helper]$ md5sum MicrobiomeHelper_amplicon_v0.4.ova
ef6f305be7c81454994598f56a9372d8  MicrobiomeHelper_amplicon_v0.4.ova

But i cannot install the ova in Virtual Box, i din't have problems with
previous versions,

thanks

**Comment by gavinmdouglas** [comment]
What error are you getting?

**Comment by cristianrohr** [comment]
Error opening the OVA file 'MicrobiomeHelper_amplicon_v0.4.ova'
(VERR_FILE_NOT_FOUND).


Código Resultado:

VBOX_E_IPRT_ERROR (0x80BB0005)

Componente:

ApplianceWrap

Interfaz:

IAppliance {8398f026-4add-4474-5bc3-2f9f2140b23e}

**Comment by gavinmdouglas** [comment]
Hmm I'm not sure what's causing that error. I've been able to install those OVA files on two different computers (Windows and Mac). What OS are you using and do you have the latest version of Virtual Box?

**Comment by cristianrohr** [comment]
Hello Gavin,
these are the versions:

[crohr@z800 50_gbs_analisys]$ rpm --query centos-release
centos-release-7-3.1611.el7.centos.x86_64
[crohr@z800 50_gbs_analisys]$ virtualbox -h
Oracle VM VirtualBox Manager 5.1.22

thanks

**Comment by cristianrohr** [comment]
I updated the VirtualBox version, and now i'm able to install MH correctly

**Comment by gavinmdouglas** [comment]
I'm glad to hear that!
