### ISSUE TITLE
scons: building terminated because of errors.

### ISSUE THREAD

**Issue by yjiakang** [LangilleLab/microbiome_helper#39]
I did metagenomic analysis in the microbiome_helper virtualbox, after blastx my concatenated pair-end reads against kegg.reduced.dmnd database and linking the result file into /home/shared/humann-0.99/input, then I run "scons  -j 4 " in the /home/shared/humann-0.99/. However I got an error:
**'''Results are saved in file: /dev/null
Details are saved in file: /tmp/tmpMpZe0_
scons: building terminated because of errors.'''**
Can anyone help?

**Comment by gavinmdouglas** [comment]
Hi @yjiakang,

It's difficult to troubleshoot this error without more info - was a logfile created or were any other details written to the screen?

I would suggest you shift to using HUMAnN2, which is a greatly improved approach for functional profiling and doesn't use `scons`.

**Comment by yjiakang** [comment]
There were no more info, and I have tried HUMAnN2. When I want to use the legacy database "kegg“ according to the user manual, however,  a compatible sequence database (referred to as **genes.pep** below) is needed. I cannot get the genes.pep though I have tried many ways. Would it  be convenient for you to send me a "gene.pep" copy to me?  Thanks in advance.

**Comment by yjiakang** [comment]
@gavinmdouglas

**Comment by gavinmdouglas** [comment]
@yjiakang could you email me at:
![gmail_screenshot](https://user-images.githubusercontent.com/12489683/61056857-79946380-a3ca-11e9-8593-2172916b05bb.jpg)

Thanks

**Comment by yjiakang** [comment]
@gavinmdouglas it is difficult for me to send a gmail because of the inaccessibility to the foreign network. I use QQ email instead. It is: 
1652750913@qq.com

**Comment by gavinmdouglas** [comment]
Hey @yjiakang,

You can download the last free version (v56) of the KEGG sequence database here:
https://www.dropbox.com/s/awa46dar435nn0w/kegg.reduced.fasta.tar.bz2?dl=1

I believe you can swap in that decompressed file for genes.pep in their examples.

**Comment by yjiakang** [comment]
@gavinmdouglas Thanks a lot.
