### ISSUE TITLE
--omit_columns option in collapse_table.py

### ISSUE THREAD

**Issue by danielm710** [LangilleLab/microbiome_helper#46]
I have a question about FAPROTAX.

My ASV table header is formatted something like the following:
```
# It's tab separated
rowID   Feature ID    Sample1    Sample2    Consensus.Lineage    ReprSequence
```

It looks like --omit-columns works well with positive indices, but doesn't seem to work on negative indices. In my case, ReprSequence column will always be in the last column, and the number of samples vary per analysis. 

I was just wondering if specifying negative indices for --omit_columns will be supported in the future version? Perhaps, it's already possible to specify negative indices, but I'm just doing something wrong?

Thanks in advance.

### Python version
Python 3.6.7

### FAPROTAX version
1.2.1 (latest as of 2020 Jan.)

**Comment by gavinmdouglas** [comment]
Hi @danielm710,

We're actually not the FAPROTAX maintainers or developers so we wont be modifying that script. You can find the author's website here: https://pages.uoregon.edu/slouca/LoucaLab/archive/FAPROTAX/lib/php/index.php?section=Instructions
