### ISSUE TITLE
microbiomehelper and qiime 2020 

### ISSUE THREAD

**Issue by turbo4xl** [LangilleLab/microbiome_helper#48]
microbiomehelper come with qiime2 2018 how do i upgrade that to qiime 2020 thanks

**Comment by gavinmdouglas** [comment]
Hi @turbo4xl,

The easiest thing to do would be to install the latest QIIME 2 by following these instructions: https://docs.qiime2.org/2020.2/install/native/#install-qiime-2-within-a-conda-environment


Best,

Gavin
