### ISSUE TITLE
ARGs annotation

### ISSUE THREAD

**Issue by mhmism** [LangilleLab/microbiome_helper#49]
Is there a pipeline that I can follow to annotate/assign antibiotic resistance genes (ARGs) using microbiome helper?

**Comment by gavinmdouglas** [comment]
Hi @mhmism,

There isn't a pipeline to do that specifically on the wiki. You may want to look into the [Comprehensive Antibiotic Resistance Database (CARD)](https://card.mcmaster.ca/) to see if any of their resources would suit your purposes! 

Also, I know that a [pipeline for identifying ARGs in metagenomics data specifically](https://github.com/beiko-lab/AMRtime) is being developed by others, but I'm not sure what stage of development they are at currently.
