### ISSUE TITLE
Improving Faprotax returns

### ISSUE THREAD

**Issue by GarthWatson** [LangilleLab/microbiome_helper#50]
In the report output I am getting less than 50% of my OTUs mapping to function. Is that what I am to accept of are there configuarble settings to improve that?

**Comment by gavinmdouglas** [comment]
Hi @GarthWatson,

I'm not sure whether that range is reasonable or not - I would recommend you touch base with the Faprotax author to ask about configuration.


Best,

Gavin

**Comment by GarthWatson** [comment]
Thanks for that. Had not thought of that myself!

________________________________
