### ISSUE TITLE
parallel Unknown option: link

### ISSUE THREAD

**Issue by soilmicrobiome** [LangilleLab/microbiome_helper#55]
I am using running parallel version 20160722.  But when i use the command;

_parallel -j 4 --link 'cat {1} {2} > raw_data_cat/{1/.}_cat.fastq' ::: raw_data/*.fastq ::: raw_data_rc/*_rc.fastq_

I get "_parallel Unknown option: link_" returned.

For the tutorial - what version of parallel is the link option used in?  Wondering if the command was replace in a different version?

Thanks for any help

**Comment by gavinmdouglas** [comment]
Those commands have been run with a few different versions of parallel, but I can confirm that the option is present in version 20170722, so I would recommend upgrading your version.
