### ISSUE TITLE
Scripts for Metagenome SOP v3

### ISSUE THREAD

**Issue by rachelmugge** [LangilleLab/microbiome_helper#56]
Hi,
I've installed the latest version of MBH and I am following the steps for version 3 of the metagenomics workflow, but I cannot find the scripts used in the MMSeqs2 section- are these still under development? Or can you point me to where I can find them?

Thanks!

**Comment by rachelmugge** [comment]
Perfect, thanks so much!

**Comment by rachelmugge** [comment]
Another question:

What is the best way to adjust parameters for the 'mmseqs search' command within a job file? I've created the job files and the first one seems to run okay (I chose the option of running one at a time), but if I open the job file and manually change parameters such as `--threads`, `-a`, `-s`, etc., the job file then won't execute. Are the parameters something I should edit within the 'run_TaxonomyFunctionSearchMegan.pl' script instead?

**Comment by dhwanidesai** [comment]
Hi Rachel,
Modifying the jobfile manually to change parameters should work, if you specified the mmseqs parameters correctly, because basically the jobfile is just a shell script running those commands.
Is there a specific error message you get when running a modified jobfile?

Could you send me the error message that you get?

regards,
Dhwani

________________________________

**Comment by rachelmugge** [comment]
Hi Dr. Desai,
Okay, that's what I thought- this is the error:

`-bash: /Users/firefly-hl/mmseqs-B001-S3-2022-07-22-11-53-42-jobfile_edited.sh: Operation not permitted`

I suspect it's a permissions error on my machine, not an issue with the script. I've tried changing the read and write permissions for the individual job file as well as giving the terminal application full disk access, both with no luck. I can still run the mmseqs steps individually so it's not a big issue, but creating and running job files, as in the tutorial, seems more efficient with multiple samples.

Thanks,
Rachel

**Comment by rachelmugge** [comment]
To follow-up on this, I am able to run each edited job file individually by moving the job files from the hard drive to the SSD (not sure if that made a difference), and then dragging and dropping into the terminal instead of running `./mmseqs-*.sh`
