### ISSUE TITLE
mSystem paper datasets are unaccessible

### ISSUE THREAD

**Issue by Zuopeng94** [LangilleLab/microbiome_helper#57]
Hi, I'm a beginner for microbiome, and think your paper is indeed helpful for me to learn the related knowledges. How the links of paper data are unaccessible, could you please send the mSystem  paper data to me  or update the link?

**Comment by amcomeau** [comment]
We were having some problems with the public Dropbox links, but they should be active now again. Please try again and let us know.


[cid:8f6bab69-8727-4f0c-993a-f33a6b9d74a2]<https://imr.bio>

ANDRÉ M. COMEAU, PhD
Manager • Integrated Microbiome Resource (IMR)
T: 902.494.2684 | E: ***@***.******@***.***>

​Address for deliveries:
Dept. of Pharmacology
Tupper Med. Bldg., room 5D
Dalhousie University
5850 College St.
Halifax NS B3H 4R2

​[cid:4c3849bc-92bb-42c2-9110-37c120b9fb04]<http://morganlangille.com>

Research Associate (Lab Manager)

Morgan Langille Lab<http://morganlangille.com> • Dept. of Pharmacology
ResearchGate Profile<http://www.researchgate.net/profile/Andre_Comeau> • GoogleScholar Publications <http://scholar.google.ca/citations?hl=en&user=-K-N4ssAAAAJ> <http://scholar.google.ca/citations?hl=en&user=-K-N4ssAAAAJ>


"Without fantasy, there is no science. Without fact, there is no art." - Nabokov
"The good thing about science is that it's true whether or not you believe in it." - Neil deGrasse Tyson

________________________________
From: Zuopeng94 ***@***.***>
Sent: Friday, December 9, 2022 4:50 AM
To: LangilleLab/microbiome_helper ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LangilleLab/microbiome_helper] mSystem paper datasets are unaccessible (Issue #57)

CAUTION: The Sender of this email is not from within Dalhousie.

Hi, I'm a beginner for microbiome, and think your paper is indeed helpful for me to learn the related knowledges. How the links of paper data are unaccessible, could you please send the mSystem paper data to me or update the link?

**Comment by nearinj** [comment]
Issu
