### ISSUE TITLE
Why "Use of uninitialized value in join or string" error?

### ISSUE THREAD

**Issue by wanglu2014** [LangilleLab/microbiome_helper#59]
![图片](https://user-images.githubusercontent.com/12541282/207280182-b4c2eea1-ee28-45a8-8078-769defa05315.png)
I already have fastq files.
Thank you for your attention!

**Comment by R-Wright-1** [comment]
Hello, I don't remember if you also asked about this issue in the Google group or not, but I believe it would be solved by deactivating the environment first with `conda deactivate` (if you are following one of the IMPACTT metagenome tutorials then this step should come first in the instructions) and then activating the environment again - it looks like yours is called `Metag` so running `conda activate Metag` should do it.
